apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: iot-demo
  namespace: demo
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: iot-demo
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: iot-message-dumper