apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: scale
  namespace: demo
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          containerConcurrency: 1
          container:
            image: gcr.io/cloudylabs-public/maxprime:0.2.1
            resources:
              limits:
                memory: "256Mi"
                cpu: "1"
            env:
              - name: T_VERSION
                value: "0.2.1"
