apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: bg
  namespace: demo
spec:
  template:
    metadata:
      name: bg-1
    spec:
      containers:
        - image: gcr.io/knative-samples/knative-route-demo:blue
          env:
            - name: T_VERSION
              value: blue
