apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: vision
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/cloudylabs/vision:3.2.10
