apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: config
  namespace: demo
spec:
  template:
    spec:
      containerConcurrency: 60
      containers:
        - image: gcr.io/knative-samples/ktest:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.5"
              # nvidia.com/gpu: 1
            limits:
              memory: "256Mi"
              cpu: "1"
          env:
            - name: RELEASE
              value: "v0.6.7-config"
            - name: LOG_TO_FILE
              value: "yes"
